### ISSUE TITLE
[Feature 2] Reporting system

### ISSUE THREAD

**Issue by nathan-1022** [CSC207-2022F-UofT/course-project-choose#10]
The reporting system allows users to report other users. The reported users will be banned and cannot create new accounts using the same email addresses if they're reported for sufficient number of times. 

First pull request for review: Nov 4th.
Second pull request based on feedback within the team: Nov 11th.
Complete: Nov 21st.

Reviewers: Chao-Ma-910, ShuHaoLin2002, hzhqwq

**Comment by cyltaracai** [comment]
The work is merged to the main branch already
